//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvCable.Conciliacion.WinService.TvCableConciliacionWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TvCableConciliacionWebService.ITvCableConciliacionServices")]
    public interface ITvCableConciliacionServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvCableConciliacionServices/RegistrarArchivoConciliacionMdp", ReplyAction="http://tempuri.org/ITvCableConciliacionServices/RegistrarArchivoConciliacionMdpRe" +
            "sponse")]
        string RegistrarArchivoConciliacionMdp(string nombreArchivo, string fechaTransacciones, string codigoMdp, int numTransacciones, decimal montoTotal, string mailNotificacion, string observaciones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITvCableConciliacionServicesChannel : TvCable.Conciliacion.WinService.TvCableConciliacionWebService.ITvCableConciliacionServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TvCableConciliacionServicesClient : System.ServiceModel.ClientBase<TvCable.Conciliacion.WinService.TvCableConciliacionWebService.ITvCableConciliacionServices>, TvCable.Conciliacion.WinService.TvCableConciliacionWebService.ITvCableConciliacionServices {
        
        public TvCableConciliacionServicesClient() {
        }
        
        public TvCableConciliacionServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TvCableConciliacionServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvCableConciliacionServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvCableConciliacionServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegistrarArchivoConciliacionMdp(string nombreArchivo, string fechaTransacciones, string codigoMdp, int numTransacciones, decimal montoTotal, string mailNotificacion, string observaciones) {
            return base.Channel.RegistrarArchivoConciliacionMdp(nombreArchivo, fechaTransacciones, codigoMdp, numTransacciones, montoTotal, mailNotificacion, observaciones);
        }
    }
}
