//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebFormResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebFormResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTIÓN DE PAGO.
        /// </summary>
        internal static string lbltitobservacion {
            get {
                return ResourceManager.GetString("lbltitobservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBSERVACIÓN:.
        /// </summary>
        internal static string ltitActuObservacion {
            get {
                return ResourceManager.GetString("ltitActuObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha afectado ningún registro.
        /// </summary>
        internal static string mdgNoafectado {
            get {
                return ResourceManager.GetString("mdgNoafectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha requerida.
        /// </summary>
        internal static string msgFechareq {
            get {
                return ResourceManager.GetString("msgFechareq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha  podido insertar Historial para Intermix.
        /// </summary>
        internal static string msgInsertHisIntermixKo {
            get {
                return ResourceManager.GetString("msgInsertHisIntermixKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido registra el  Historial Estado.
        /// </summary>
        internal static string msgInsertHistorialKo {
            get {
                return ResourceManager.GetString("msgInsertHistorialKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha registro Intermix registro.
        /// </summary>
        internal static string msginsertInterxKo {
            get {
                return ResourceManager.GetString("msginsertInterxKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos para insertar Intermix.
        /// </summary>
        internal static string msgInsertInterxNull {
            get {
                return ResourceManager.GetString("msgInsertInterxNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos seleccionados se enviaron correctamente a Intermix.
        /// </summary>
        internal static string msgInsertInterxOk {
            get {
                return ResourceManager.GetString("msgInsertInterxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se tuvo éxito al inserta en Intermix verifique con el Administrador.
        /// </summary>
        internal static string msgIntermixKo {
            get {
                return ResourceManager.GetString("msgIntermixKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de ítems a mostrar:.
        /// </summary>
        internal static string msglblnumeroitems {
            get {
                return ResourceManager.GetString("msglblnumeroitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas en la página.
        /// </summary>
        internal static string msglblnumpag {
            get {
                return ResourceManager.GetString("msglblnumpag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos que mostrar..
        /// </summary>
        internal static string msgNullDataGrill {
            get {
                return ResourceManager.GetString("msgNullDataGrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha  podido llenar la Grilla de información consulte con el administrador.
        /// </summary>
        internal static string msgNullGrilla {
            get {
                return ResourceManager.GetString("msgNullGrilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado ningún ítem.
        /// </summary>
        internal static string msgNullItem {
            get {
                return ResourceManager.GetString("msgNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede seleccionar los ítems error:.
        /// </summary>
        internal static string msgNullItemError {
            get {
                return ResourceManager.GetString("msgNullItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Ítems seleccionados:.
        /// </summary>
        internal static string msgnumItems {
            get {
                return ResourceManager.GetString("msgnumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas al procesas.
        /// </summary>
        internal static string msgScriptError {
            get {
                return ResourceManager.GetString("msgScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar observaciones para ese ítem.
        /// </summary>
        internal static string msgScriptErrorH {
            get {
                return ResourceManager.GetString("msgScriptErrorH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos seleccionados han sido actualizados.
        /// </summary>
        internal static string msgScriptOk {
            get {
                return ResourceManager.GetString("msgScriptOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha  podido sumar lo montos.
        /// </summary>
        internal static string msgSumaError {
            get {
                return ResourceManager.GetString("msgSumaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   Registros han sido cambiados.
        /// </summary>
        internal static string msgUpdateconci {
            get {
                return ResourceManager.GetString("msgUpdateconci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha  podido actualizar los Ítems para Conciliacion.
        /// </summary>
        internal static string msgUpdateConciliacionKo {
            get {
                return ResourceManager.GetString("msgUpdateConciliacionKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTIÓN DE PAGO.
        /// </summary>
        internal static string tidetalleConci {
            get {
                return ResourceManager.GetString("tidetalleConci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONCILIACIÒN.
        /// </summary>
        internal static string tiPanelDetalle {
            get {
                return ResourceManager.GetString("tiPanelDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Conciliación:.
        /// </summary>
        internal static string tipConci {
            get {
                return ResourceManager.GetString("tipConci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha fin:.
        /// </summary>
        internal static string tipFechafin {
            get {
                return ResourceManager.GetString("tipFechafin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio estado:.
        /// </summary>
        internal static string titActuEstado {
            get {
                return ResourceManager.GetString("titActuEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar pagos.
        /// </summary>
        internal static string titBtbuscarPagos {
            get {
                return ResourceManager.GetString("titBtbuscarPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar estado.
        /// </summary>
        internal static string titBtCambioestado {
            get {
                return ResourceManager.GetString("titBtCambioestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar estados.
        /// </summary>
        internal static string titBtCambioestadovarios {
            get {
                return ResourceManager.GetString("titBtCambioestadovarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar archivo Intermix.
        /// </summary>
        internal static string titBtfileInternixs {
            get {
                return ResourceManager.GetString("titBtfileInternixs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Intermix.
        /// </summary>
        internal static string titbtInsertarIntermix {
            get {
                return ResourceManager.GetString("titbtInsertarIntermix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar estado.
        /// </summary>
        internal static string titBtrechpagos {
            get {
                return ResourceManager.GetString("titBtrechpagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio estado:.
        /// </summary>
        internal static string titCambioestado {
            get {
                return ResourceManager.GetString("titCambioestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string titCerraSesion {
            get {
                return ResourceManager.GetString("titCerraSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright.
        /// </summary>
        internal static string titCopyright {
            get {
                return ResourceManager.GetString("titCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados..
        /// </summary>
        internal static string titderechos {
            get {
                return ResourceManager.GetString("titderechos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPRESA FACTURADORA:.
        /// </summary>
        internal static string titEmpresaFactura {
            get {
                return ResourceManager.GetString("titEmpresaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA EMISIÓN:.
        /// </summary>
        internal static string titFechaEmision {
            get {
                return ResourceManager.GetString("titFechaEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio:.
        /// </summary>
        internal static string titfechaini {
            get {
                return ResourceManager.GetString("titfechaini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID:.
        /// </summary>
        internal static string titID {
            get {
                return ResourceManager.GetString("titID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intermix.
        /// </summary>
        internal static string titInternix {
            get {
                return ResourceManager.GetString("titInternix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBSERVACIÓN:.
        /// </summary>
        internal static string titInterObservacion {
            get {
                return ResourceManager.GetString("titInterObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTIÓN DE PAGO.
        /// </summary>
        internal static string titItemasVarios {
            get {
                return ResourceManager.GetString("titItemasVarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MDP.
        /// </summary>
        internal static string tiTituloMdp {
            get {
                return ResourceManager.GetString("tiTituloMdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TUV.
        /// </summary>
        internal static string tiTituloTuv {
            get {
                return ResourceManager.GetString("tiTituloTuv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBSERVACIÓN:.
        /// </summary>
        internal static string titObservacion {
            get {
                return ResourceManager.GetString("titObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor:.
        /// </summary>
        internal static string titRecaudador {
            get {
                return ResourceManager.GetString("titRecaudador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola  .
        /// </summary>
        internal static string titSaludo {
            get {
                return ResourceManager.GetString("titSaludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA:.
        /// </summary>
        internal static string titTituloFecha {
            get {
                return ResourceManager.GetString("titTituloFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MONTO:.
        /// </summary>
        internal static string titTituloMonto {
            get {
                return ResourceManager.GetString("titTituloMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLIENTE:.
        /// </summary>
        internal static string titTituloUsuario {
            get {
                return ResourceManager.GetString("titTituloUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final no puede ser menor a fecha inicial.
        /// </summary>
        internal static string titvalidatorFecha {
            get {
                return ResourceManager.GetString("titvalidatorFecha", resourceCulture);
            }
        }
    }
}
